# Generated by Django 5.0.2 on 2024-02-09 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_date', models.DateField(default=datetime.date.today)),
                ('website_name', models.CharField(max_length=50)),
                ('website_url', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(choices=[('', 'Select Email Address'), ('a@a.com', 'a@a.com'), ('b@b.com', 'b@b.com'), ('c@c.com', 'c@c.com'), ('d@d.com', 'd@d.com'), ('e@e.com', 'e@e.com'), ('f@f.com', 'f@f.com'), ('g@g.com', 'g@g.com'), ('h@h.com', 'h@h.com'), ('i@i.com', 'i@i.com'), ('j@j.com', 'j@j.com')], max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
